config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ads#index'

  get 'users' => 'users#index'

  get '/users/:id', to: 'users#show', as: 'user'

  resources :ads do 
  	resources :comments
  end	
	
  post 'add' => 'comments#create'

end

app/models/ad.rb
class Ad < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	default_scope { order(created_at: :asc) }
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
	before_action :authenticate_user!, :except => [:show, :index]

	def index
		@ads = Ad.all

		if params[:search]
			@ads = Ad.joins("INNER JOIN users ON users.id = ads.user_id")
			@ads = @ads.where("ads.name ILIKE ?", "%#{params[:search]}%")
									.or(@ads.where("ads.text ILIKE ?", "%#{params[:search]}%"))
									.or(@ads.where("users.login ILIKE ?", "%#{params[:search]}%"))
									.or(@ads.where("users.address ILIKE ?", "%#{params[:search]}%"))
									.or(@ads.where("users.full_name ILIKE ?", "%#{params[:search]}%"))
		end
	end

	def new
		@ad = Ad.new
	end

	def show
		@ad = Ad.find(params[:id])

		@comment = Comment.new
	end

	def edit
		@ad = Ad.find(params[:id])		
	end

	def update
		@ad = Ad.find(params[:id])	

		if @ad.update(form_params)
			redirect_to @ad
		end
	end

	def destroy
		@ad = Ad.find(params[:id])

		if @ad.destroy
			redirect_to root_path
		end	
	end

	def create	
		@user = User.find(current_user.id)
		@ad = @user.ads.build(form_params)

		if @ad.save
			redirect_to @ad
		end	
	end

	private def form_params
		params.require(:ad).permit(:name, :text, :image)
	end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/views/ads/edit.html.erb
<div class="panel" id="ad-form">
	<h3>Редактирование объявления "<%= @ad.name %>"</h3>
		<%= form_for @ad, url: ad_path(@ad.id), method: :patch, html: { multipart: true } do |f| %>
			<div class="field">
				<%= f.text_field :name, :placeholder => "Название" %>
			</div>

			<div class="field">
				<%= f.text_area :text, :placeholder => "Текст объявления" %>
			</div>

			<div class="field">
				<%= f.label :image, 'Изображение' %><br />
				<%= f.file_field :image %>
			</div>

			<div class="field">
				<%= f.submit "Изменить", :id => "submit_button" %>
			</div>
	<% end %>
</div>

app/views/ads/index.html.erb
<%= form_tag(root_path, :method => "get", id: "search-form") do %>
	<%= text_field_tag :search, params[:search], placeholder: "Поиск" %> 
	<%= submit_tag "Найти", id: "submit_button" %>
<% end %>

<% if params[:search] %>
	<% if @ads.length == 0 %>
		<h3 style="margin-bottom: 20px">По запросу "<%= params[:search] %>" ничего не найдено </h3>		
	<% else %>	
		<h3 style="margin-bottom: 20px">Результаты по запросу "<%= params[:search] %>": </h3>
	<% end %>	
<% end %>

<% @ads.each do |ad| %>
	<div class="ad-preview panel clearfix">
		<%= link_to ad.name, ad_path(ad.id), class: "preview-header-link" %>
		<%= image_tag ad.image.url(:thumb), class: "preview-image" %>
		<p style="font-size: 15px" class="word-wrap"><%= ad.text %></p>
		<b>Разместил: </b> <%= ad.user.full_name %>, <i> <%= link_to ad.user.login, user_path(ad.user.id) %> </i> <br>
	</div>	
<% end %>

app/views/ads/new.html.erb
<div class="panel" id="ad-form">
	<h3>Новое объявление</h3>
		<%= form_for @ad, url: {action: "create"}, html: { multipart: true }, authenticity_token: true do |f| %>
			<div class="field">
				<%= f.text_field :name, :placeholder => "Название" %>
			</div>

			<div class="field">
				<%= f.text_area :text, :placeholder => "Текст объявления" %>
			</div>

			<div class="field">
				<%= f.label :image, 'Изображение' %><br />
				<%= f.file_field :image %>
			</div>

			<div class="field">
				<%= f.submit "Добавить", :id => "submit_button" %>
			</div>
	<% end %>
</div>

app/views/ads/show.html.erb
<div class="ad-overview panel clearfix">
	<h2 class="headline"><%= @ad.name %></h2>
	<div class="clearfix">
		<%= link_to @ad.image.url, :target => "_blank", class: "overview-image" do %>
			<%= image_tag @ad.image.url(:medium) %>
		<% end %>
		<p class="overview-text"><%= @ad.text %></p>
	</div>

	<div class="user-info">
		<b>Разместил: </b> <%= @ad.user.full_name %>, <i> <%= link_to @ad.user.login, user_path(@ad.user.id) %> </i> <br>
		<b>Адрес: </b>  <%= @ad.user.country %>, <%= @ad.user.state %>, <%= @ad.user.city %>, <%= @ad.user.address %>
	</div>

	<% if user_signed_in? %>
		<% if current_user.login == @ad.user.login %>

			<%= button_to "Редактировать", edit_ad_path(@ad.id), method: :get, class: "edit-btn" %>

			<%= button_to "Удалить", ad_path(@ad.id), data: { confirm: "Вы уверены?" }, method: :delete, class: "delete-btn" %>

		<% end %>
	<% end %>
</div>		

<div class="panel">

	<div id="comments">
		<%= render partial: 'comments/comments' %>
	</div>

	<div id="add-comment">
		<% if user_signed_in? %>

			<h3>Добавить комментарий</h3>
			<%= form_for @comment, url: ad_comments_path(@ad.id), html: { multipart: true }, remote: true do |f| %>

				<div class="field">
					<%= f.text_area :message, :placeholder => "Сообщение" %>
				</div>

				<div class="field">
					<%= f.label :image, 'Изображение' %><br />
					<%= f.file_field :image, :id => "image-upload" %>
				</div>

				<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
				
				<div class="field">
					<%= f.submit "Добавить", :id => "submit_button" %>
				</div>
			<% end %>	

		<% else %>	
			<h3><%= link_to 'Войдите', new_user_session_path %>, чтобы комменитровать</h3>
	</div>

	<% end %>
</div>