config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'ads#index'

  get 'users' => 'users#index'

  get '/users/:id', to: 'users#show', as: 'user'

  resources :ads do 
  	resources :comments
  end	
	
  post 'add' => 'comments#create'

end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :ad

	belongs_to :user

	has_attached_file :image, :styles => { :medium => "200x200>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates_length_of :message, :maximum => 300

	default_scope { order(id: :asc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, :except => [:show, :index]

	def create
		@ad = Ad.find(params[:ad_id])

		@comment = @ad.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save
			respond_to do |format|
        format.js
    	end
		end	
	end

	def edit
		@comment = Comment.find(params[:id])

		@ad = Ad.find(params[:ad_id])
	end

	def update
		@comment = Comment.find(params[:id])	

		if @comment.update(comment_params)
			redirect_to Ad.find(params[:ad_id])
		end
	end

	def destroy
		@ad = Ad.find(params[:id])
		@comment = Comment.find(params[:ad_id])

		if @comment.destroy
			respond_to do |format|
        format.js
    	end
		end	
	end

	private def comment_params
		puts params
		params.require(:comment).permit(:message, :image)
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<h3>Комментарии</h3>

<% if @ad.comments.length == 0 %>
	<div class="comment-section">
		<p>Комментариев пока нет</p>
	</div>
<% else %>	
	<% @ad.comments.each do |comment| %>
		<div class="comment-section clearfix">
			<p> <%= link_to comment.user.login, user_path(comment.user.id) %>: <%= comment.message %></p>

			<% if comment.image.exists? %>
				<%= link_to comment.image.url, :target => "_blank", class: "comment-image" do %>
					<%= image_tag comment.image.url(:medium) %>
				<% end %>
			<% end %>


			<% if user_signed_in? %>
				<% if current_user.login == comment.user.login %>
						<%= button_to "Редактировать", edit_ad_comment_path(@ad.id, comment.id), method: :get, class: "edit-btn" %>

						<%= button_to "Удалить", ad_comment_path(comment.id, @ad.id), data: { confirm: "Вы уверены?" }, remote: true, method: :delete, class: "delete-btn" %>
				<% end %>
			<% end %>
		</div>
	<% end %>
<% end %>

app/views/comments/create.js.erb
$('#comments').html("<%= escape_javascript (render partial: 'comments/comments') %>");

app/views/comments/destroy.js.erb
$('#comments').html("<%= escape_javascript (render partial: 'comments/comments') %>");

app/views/comments/edit.html.erb
<div id="edit-comment">
		<h3>Редактирование комментария</h3>

		<%= form_for @comment, url: ad_comment_path(@ad.id, @comment.id), method: :patch, html: { multipart: true } do |f| %>

			<div class="field">
				<%= f.text_area :message, :placeholder => "Сообщение" %>
			</div>

			<div class="field">
				<%= f.label :image, 'Изображение' %><br />
				<%= f.file_field :image, :id => "image-upload" %>
			</div>

			<div class="field">
				<%= f.submit "Изменить", :id => "submit_button" %>
			</div>
		<% end %>	
</div>